version: 2
updates:
  # Maintain dependencies for docker
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "09:15"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
    labels:
      - "dependencies"
      - "docker"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "09:15"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
    labels:
      - "dependencies"
      - "github-actions"
